language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t luis/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true luis/docker-react npm run test

deploy:
    prrovider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "docker-react"
    env: "DockerReact-env-2"
    bucket_name: "elasticbeanstalk-ap-northeast-1-373567329083"
    bucket_path: "docker-react"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
on:
    branch: master

